Non architecture
EntryDSM/Chanel pull request #3
Opened 2019-07-16 06:37 UTC by by09115

다음과 같은 변동 사항이 적용되었습니다.
- 아키텍쳐 적용 해제
- endpoint 구현
- email 전송 기능 구현
- travisci/dockerize

2019-07-16 06:56 UTC, Gaegul approved these changes

2019-07-16 06:56 UTC, Gaegul commented on chanel/authentication.py
> +
다른 class와 차이나게 이부분에 띄워쓰기가 들어가있습니다 이유가 없다면 스타일을 맞춰주는게 어떨까요

2019-07-16 09:42 UTC, NovemberOscar commented
다음부터는 PR의 규모를 좀 줄여 줬으면 좋겠어요~ 그리고 제목은 아키텍처 셋업인데 엔드포인트, 배포, 빌드까지 너무 많은 내용이 한번에 들어가 있네요. 이러면 정말 힘듭니다.... 😢

2019-07-16 10:00 UTC, by09115 commented on chanel/authentication.py
> +
넵 수정토록 하겠습니다

2019-07-16 10:06 UTC, by09115 commented
> 다음부터는 PR의 규모를 좀 줄여 줬으면 좋겠어요~ 그리고 제목은 아키텍처 셋업인데 엔드포인트, 배포, 빌드까지 너무 많은 내용이 한번에 들어가 있네요. 이러면 정말 힘듭니다.... 😢

네 다음부터는 PR의 규모를 줄이도록 하겠습니다. 죄송해요 ㅠㅠ

2019-07-29 13:52 UTC, rscarrera27 requested changes

2019-07-29 13:52 UTC, NovemberOscar commented on chanel/authentication.py
> +                value=str({"refresh": refresh}),
refresh만 저장할 목적이면 json 형태가 아니라 그냥 str만 저장해도 됩니다. 그리고 json을 저장하고 싶으면 ujson 이나 json의 dumps를 써야지 str로 저장하는것은 안됩니다.

2019-07-29 13:52 UTC, NovemberOscar commented on chanel/authentication.py
> +        refresh = request.headers["X-Refresh-Token"]
headers.get을 사용하도록 하고 None일 경우를 체크해 주세요

```python
if not refresh:
	raise BadRequest
```

2019-07-29 13:52 UTC, NovemberOscar commented on chanel/authentication.py
> +        elif not refresh:
request.headers.get을 사용해야 이 코드에 도달하겠죠? 지금 그대로라면 에러가 날 뿐...

2019-07-29 13:52 UTC, NovemberOscar commented on chanel/authentication.py
> +                role=(await admin_info.json())["admin_type"],
admin_type이 만약 없을 경우에는 에러가 나겠네요

2019-07-29 13:52 UTC, NovemberOscar commented on chanel/authentication.py
> +                key=f"""{SERVICE_NAME}:{(await admin_info.json())["admin_type"]}:{admin_id}""",
여기도 에러날듯

2019-07-29 13:52 UTC, NovemberOscar commented on chanel/authentication.py
> +        admin_id = request.json["admin_id"]
여기부터 다 get을 안쓰기 때문에 완벽한 페이로드가 아니면 KeyError나면서 에러날듯 합니다

2019-07-29 13:52 UTC, NovemberOscar commented on chanel/authentication.py
> +            return json("", status=202)
json이 아니라 HTTPResponse 204 일듯? No Content니까

2019-07-29 13:54 UTC, NovemberOscar commented
1차 리뷰 총평

@by09115 
지금 전체적으로 에러핸들링에 대한 부분이 전혀 고려되고 있지 않아보입니다. 지금 같은 코드가 올라가면 만약 클라이언트에서 제대로 페이로드가 안날라온다? 그럼 다 5xx code with KeyError날것같아보이네요. 거기다 라인 스페이싱도 제대로 안되어 있어서 보기가 좀 힘든 감이 있습니다.

2019-07-29 13:56 UTC, NovemberOscar commented
그리고 지금 제가 훑어보기만 했는데도 눈에 보이는 문제점이 산적해 있는데 어떻게 Approve누르신 거죠... @Gaegul ...

2019-07-30 01:05 UTC, rscarrera27 requested changes
2차 리뷰 드립니다.

전체적으로 포스트맨으로 테스트라도 해봤더라면 바로 잡을 수 있었을 것 같았던 에러가 자꾸 보이고 반환 값에 일관성이 없습니다. 그리고 hermes 코드 copy&paste 한 부분이 보이는데 chanel에서 제대로 쓰려고 안하고 그냥 copy&paste 만 한것같네요. 

예를 들면 RedisConnection에서는 json.loads를 쓰는데 redis set 할때 ㄱ그냥 str()로 박는다던가.

그리고 에러핸들링을 너무 다 대충한것같아요. 에러를 단순히 캐치해서 프린트 한다던가. 이러면 절대 안됩니다

2019-07-30 01:05 UTC, rscarrera27 commented on chanel/mail.py
> +        print(str(e))
이런건 프린트가 아니라 로그를 찍어야 하고 이렇게 와일드카드로 캐치하지 말고 에러 종류별로 나눠서 에러 캐치해 주세요

2019-07-30 01:05 UTC, rscarrera27 commented on chanel/password.py
> +        verify_code = request.args["verify"][0]
여기도 없으면 KeyError

2019-07-30 01:05 UTC, rscarrera27 commented on chanel/password.py
> +                return json("", status=200)
success message를 보내 주거나 HTTPResponse 204 No Content 보내주세요

2019-07-30 01:05 UTC, rscarrera27 commented on chanel/setting.py
> +class SETTINGS:
Pascal case 로

2019-07-30 01:05 UTC, NovemberOscar commented on chanel/signup.py
> +        email = request.json["email"]
만약 없으면 에러남. get 쓰도록

2019-07-30 01:05 UTC, NovemberOscar commented on chanel/signup.py
> +            return json({"status": "temporary user has created."}, 202)
어디는 status message 페이로드로 보내고 어디는 안보내고... 일관성 맞춰 주세요

2019-07-30 01:05 UTC, NovemberOscar commented on chanel/signup.py
> +                return json("", status=200)
여기도

2019-07-30 01:05 UTC, NovemberOscar commented on chanel/signup.py
> +                "email": temp_user.email,
dict 일 텐데 어떻게 이렇게 쓰죠?

2019-07-30 01:12 UTC, Gaegul commented on chanel/authentication.py
> +            return json("", status=202)
오류가 날 것 같은데 혹시 json("")만 넣어도 오류가 나지 않나요? 확인해주시면 감사하겠습니다! 그리고 msg가 api 별로 일관성이 없는것 같아요

2019-07-30 01:49 UTC, by09115 commented on chanel/authentication.py
> +                value=str({"refresh": refresh}),
json을 사용하지 않는 쪽으로 수정했습니다. 조언 감사드립니다.

2019-07-30 01:56 UTC, by09115 commented on chanel/authentication.py
> +        refresh = request.headers["X-Refresh-Token"]
수정했습니다. 큰일 날 뻔 했네요 ㅠㅠ

2019-07-30 02:04 UTC, NovemberOscar commented on chanel/authentication.py
> +        refresh = request.headers["X-Refresh-Token"]
이런 곳이 한두군데가 아니에요... 하두 많아서 다 체크 못했어요

2019-07-30 03:26 UTC, by09115 commented on chanel/authentication.py
> +                role=(await admin_info.json())["admin_type"],
확인했습니다. 그냥 처음부터 다시 작성토록 하겠습니다.

2019-07-30 03:29 UTC, by09115 commented
너무 문제점이 많이 발견되어서 처음부터 다시 작성토록 하겠습니다. 
코드 리뷰 하시면서 많이 불편하셨을텐데 심려 끼쳐 드려서 죄송합니다...

2019-07-30 03:29 UTC, closed without merging